import Head from "next/head";
import { useUser } from "@clerk/nextjs";
import Image from "next/image";
import { type NextPage } from "next";
import { api } from "~/utils/api";




const ProfilePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
       <div> Profile View
        </div>
      </main>
    </>
  );
};

export default ProfilePage;
