import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { user, isSignedIn } = useUser();

  const { data } = api.post.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex flex-col items-center space-y-4">
          {!isSignedIn && (
            <SignInButton>
              <button className="px-4 py-2 bg-blue-500 text-white rounded">Sign In</button>
            </SignInButton>
          )}

          {!!isSignedIn && (
            <>
              <p className="text-white text-lg">Welcome, {user?.firstName}!</p>
              <SignOutButton>
                <button className="px-4 py-2 bg-red-500 text-white rounded">Sign Out</button>
              </SignOutButton>
            </>
          )}
        </div>
        <div>
          {data?.map((post) => (<div key = {post.id}>{post.content}</div>))}
        </div>
      </main>
    </>
  );
};

export default Home;
