import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Image from "next/image";
import { type NextPage } from "next";
import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className="flex gap-3 w-full">
      <Image 
        src={user.imageUrl} 
        alt="Profile Image" 
        width={56} 
        height={56}
        className="w-14 h-14 rounded-full"
      />
      <input type="text" placeholder="Type some emojis!" className="bg-transparent grow outline-none" />
    </div>
  )
}

const Home: NextPage = () => {
  const { user, isSignedIn } = useUser();

  const { data, isLoading } = api.post.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>

  if (!data) return <div>Something went wrong</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl"> 
          <div className="flex border-b border-slate-400 p-4">
            {!isSignedIn && (
              <SignInButton>
                <button className="flex justify-center items-center">Sign In</button>
              </SignInButton>
            )}
            {isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {[...data, ...data]?.map((post) => (<div key = {post.id} className="border-b border-slate-400 p-8">{post.content}</div>))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
